version: "3"
services:
    database:
        image: mcr.microsoft.com/mssql/server:2019-CTP2.2-ubuntu
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=3OXa0H8T3U1wLh29
        ports:
            - 1433:1433
